name: Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    types: [ opened, synchronize, reopened]
  merge_group:
    types: [checks_requested]


jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.23.4'

      - name: Run tests
        run: make test

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4.0.1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.23.4'

      - name: Setup linting
        run: curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/v1.62.2/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.62.2

      - name: Run linters
        run: make lint
