name: Update Package Cache

on:
  release:
    types: [published, created]

jobs:
  cache_release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set RELEASE_VERSION
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23.4'

      - name: Update DTE Cache
        run:  GOPROXY=proxy.golang.org go list -m github.com/peterHoburg/go-date-and-time-extension/dte@${{ env.RELEASE_VERSION }}

      - name: Update DTEGORM Cache
        run:  GOPROXY=proxy.golang.org go list -m github.com/peterHoburg/go-date-and-time-extension/dtegorm@${{ env.RELEASE_VERSION }}
